services:
  db:
    image: postgres:16
    container_name: db-deliverydash
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 3s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8003:80"

  backend:
    build: backend
    container_name: backend-deliverydash
    restart: unless-stopped
    env_file: .env
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app # For hot reload
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
