# Generated by Django 5.0.7 on 2024-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('driver', 'Driver'), ('dispatcher', 'Dispatcher')], null=True),
        ),
    ]
