# Generated by Django 5.0.7 on 2024-08-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0005_alter_delivery_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name": "Delivery", "verbose_name_plural": "Deliveries"},
        ),
    ]
