# Generated by Django 5.0.7 on 2024-07-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deliver_at', models.DateTimeField()),
                ('buyer_firstname', models.CharField(max_length=30)),
                ('buyer_lastname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[(0, 'Cash'), (1, 'Card')])),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Delivered'), (2, 'Failed')], default=0)),
            ],
        ),
    ]
